service: cors-proxy

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes  # https://github.com/serverless/serverless/issues/10944#issuecomment-1091936902
  - serverless-plugin-include-dependencies
  
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 60
  stage: dev
  region: eu-central-1
  environment:
    foo: 123

functions:
  lambda:
    name: cors-proxy
    handler: handler.corsProxy
    events:
      - http:
          path: ''
          method: get
          cors: true
      - http:
          path: ''
          method: post
          cors: true
      - http:
          path: ''
          method: put
          cors: true
      - http:
          path: ''
          method: options
          cors: true
